### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [RitchieS/zsh-exa#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by RitchieS** [comment]
Thank you for your suggestion, I've added the MIT license.

If you would like to include this plugin to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list, feel free to do so.

If there are any other issues let me know!
